INSERT INTO CATEGORIA (ID, DESCRICAO, IOF, PIS, COFINS) VALUES (1, 'VIDA', 1, 2, 3);
INSERT INTO CATEGORIA (ID, DESCRICAO, IOF, PIS, COFINS) VALUES (2, 'AUTO', 5.5, 4, 1);
INSERT INTO CATEGORIA (ID, DESCRICAO, IOF, PIS, COFINS) VALUES (3, 'VIAGEM', 2, 4, 1);
INSERT INTO CATEGORIA (ID, DESCRICAO, IOF, PIS, COFINS) VALUES (4, 'RESIDENCIAL', 4, 2.5, 3);
INSERT INTO CATEGORIA (ID, DESCRICAO, IOF, PIS, COFINS) VALUES (5, 'PATRIMONIAL', 5, 3, 2);